### ISSUE TITLE
bug: follow the start instruction but got an error

### ISSUE THREAD

**Issue by kittybest** [yashgo0018/maci-wrapper#2]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

After running `yarn install` and `yarn chain`, I ran `yarn deploy` but got this error:
![image](https://github.com/yashgo0018/maci-wrapper/assets/9023842/fa73d0d7-5d1f-4966-b431-b27722be419c)

which means the command doesn't download the zkeys, the user who wanna run this starter-kit need to find the download link by themselves.

### Expected Behavior

Add a script downloading zkeys (see package.json file in maci-integration-test)
add a command to download the zkeys before deploying contracts

**Comment by yashgo0018** [comment]
Thanks, I will update the readme.

**Comment by yashgo0018** [comment]
Updated the readme now
